# Input bindings used for testing
spring.cloud.stream.bindings.input1.destination: customerId-1
spring.cloud.stream.bindings.input1.binder: kafka
spring.cloud.stream.bindings.input2.destination: customerId-2
spring.cloud.stream.bindings.input2.binder: kafka
